# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Seelake
email: info@seelake.it
email_artmusic: info(at)artmusicgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Home of Seelake AudioStation, the only Hardware VST Player
telephone: +39 0424 503717
fax: +39 0424 506828
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.seelake.com" # the base hostname & protocol for your site, e.g. http://example.com
unsubscribe_link: "mailto:info@seelake.it?subject=unsubscribe&body=Unsubscribe"
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - Library
  - asset
  - bower_components
exclude: [vendor]

# include: ['en', 'it' ]
include: ['en' ]
# permalink: /:path/ # se uncommentato permette di avere  /as-overview/index.html 
#                     # anziche /as-overview.html

### PREZZI PRODOTTI

price-asx_std-eur: 2529
price-asx_adv-eur: 2689
price-asm_std-eur: 1234
price-asm_adv-eur: 1329
price-lc-eur: 239
price-fc-eur: 94

#### TESTI PRODOTTI
text-asx_std: AudioStation X64 Standard Configuration
text-asx_adv: AudioStation X64 Advanced Configuration
text-asm_std: AudioStation MiNi Standard Configuration
text-asm_adv: AudioStation MiNi Advanced Configuration
text-lc: LiveControl Remote Controller
text-fc: AudioStation Foot Controller





